"""Mycelium runtime: failure prevention for AI agents."""

from mycelium.action_ledger import (
    ActionLedger,
    FileLedgerStorage,
    InMemoryLedgerStorage,
    LedgerEntry,
    LedgerError,
    LedgerHardBlockError,
    LedgerPendingError,
    LedgerPollTimeoutError,
    LedgerSoftBlockError,
    LedgerStorage,
    get_ledger,
    ledger,
    ledger_sync,
    mark_crossed,
    mark_maybe_crossed,
    record_external_operation,
    renew_lease,
    side_effect,
)
from mycelium.audit_receipt import (
    AuditReceiptEmitter,
    AuditReceiptError,
    AuditReceiptRecord,
    FileAuditReceiptStorage,
    InMemoryAuditReceiptStorage,
    verify_receipt,
)
from mycelium.config import (
    ConfigError,
    MyceliumConfig,
    TransitionConfig,
    load_config,
    load_config_from_string,
)
from mycelium.history_guard import HistoryGuard, HistoryTruncatedError
from mycelium.message_validator import MessageValidationError, MessageValidator
from mycelium.protect import protect, protect_sync
from mycelium.reconcile import Reconciler, ReconcileResult, ReconcileStatus
from mycelium.session import Session
from mycelium.state_flush import (
    FileStateFlushStorage,
    InMemoryStateFlushStorage,
    StateFlush,
    StateFlushError,
    StateSnapshot,
)
from mycelium.storage.postgres_ledger import PostgresLedgerStorage, PostgresTaskLedgerStorage
from mycelium.storage.redis_ledger import RedisLedgerStorage, RedisTaskLedgerStorage
from mycelium.task_ledger import (
    TaskFileLedgerStorage,
    TaskInMemoryLedgerStorage,
    TaskLedger,
    TaskLedgerEntry,
    TaskLedgerError,
    TaskLedgerPendingError,
    TaskLedgerStorage,
    get_task_ledger,
    task_ledger,
    task_ledger_sync,
)
from mycelium.tool_boundary import (
    ToolBoundaryError,
    ToolBoundaryExhaustedError,
    bounded,
    bounded_sync,
    tool_error_message,
)
from mycelium.tool_registry import ToolRegistry
from mycelium.tool_runner import ToolRunner
from mycelium.transition import (
    LeaseValidity,
    RetryPermission,
    SideEffectBoundary,
    SideEffectClass,
    Spendability,
    TerminalOutcome,
    ToolTransitionBinding,
    TransitionScope,
    derive_transition_key,
    derive_transition_key_for_call,
    execution_scope,
    resolve_lease_validity,
)
from mycelium.transition_resolution import (
    TransitionGate,
    repair_transition_fields,
    transition_needs_repair,
)

__version__ = "1.13.2"

__all__ = [
    "ActionLedger",
    "FileLedgerStorage",
    "InMemoryLedgerStorage",
    "LedgerEntry",
    "LedgerError",
    "LedgerHardBlockError",
    "LedgerPendingError",
    "LedgerPollTimeoutError",
    "LedgerSoftBlockError",
    "LedgerStorage",
    "get_ledger",
    "ledger",
    "ledger_sync",
    "side_effect",
    "mark_maybe_crossed",
    "mark_crossed",
    "record_external_operation",
    "renew_lease",
    "Reconciler",
    "ReconcileResult",
    "ReconcileStatus",
    "AuditReceiptEmitter",
    "AuditReceiptError",
    "AuditReceiptRecord",
    "FileAuditReceiptStorage",
    "InMemoryAuditReceiptStorage",
    "verify_receipt",
    "TaskFileLedgerStorage",
    "TaskInMemoryLedgerStorage",
    "TaskLedger",
    "TaskLedgerEntry",
    "TaskLedgerError",
    "TaskLedgerPendingError",
    "TaskLedgerStorage",
    "RedisLedgerStorage",
    "RedisTaskLedgerStorage",
    "PostgresLedgerStorage",
    "PostgresTaskLedgerStorage",
    "get_task_ledger",
    "task_ledger",
    "task_ledger_sync",
    "ConfigError",
    "MyceliumConfig",
    "TransitionConfig",
    "SideEffectClass",
    "SideEffectBoundary",
    "Spendability",
    "RetryPermission",
    "TerminalOutcome",
    "LeaseValidity",
    "TransitionGate",
    "ToolTransitionBinding",
    "TransitionScope",
    "derive_transition_key",
    "derive_transition_key_for_call",
    "execution_scope",
    "resolve_lease_validity",
    "repair_transition_fields",
    "transition_needs_repair",
    "load_config",
    "load_config_from_string",
    "protect",
    "protect_sync",
    "Session",
    "StateFlush",
    "StateFlushError",
    "StateSnapshot",
    "FileStateFlushStorage",
    "InMemoryStateFlushStorage",
    "MessageValidator",
    "MessageValidationError",
    "HistoryGuard",
    "HistoryTruncatedError",
    "bounded",
    "bounded_sync",
    "ToolBoundaryError",
    "ToolBoundaryExhaustedError",
    "tool_error_message",
    "ToolRegistry",
    "ToolRunner",
    "__version__",
]
