"""Mycelium runtime: full-lifecycle reliability for AI-agent tool actions.

The public surface is resolved on first attribute access.  Keeping the
namespace here (rather than importing every subsystem) makes ``import
mycelium`` inexpensive while retaining the historical exports.
"""

from __future__ import annotations

import sys as _sys
from importlib import import_module as _import_module
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _package_version
from types import ModuleType as _ModuleType

_LAZY_IMPORTS = {
    'ADAPTER_REPORT_SCHEMA_VERSION': (
        'mycelium.provider_conformance',
        'ADAPTER_REPORT_SCHEMA_VERSION',
    ),
    'ADAPTER_REPORT_SIGNATURE_ALGORITHM': (
        'mycelium.provider_conformance',
        'ADAPTER_REPORT_SIGNATURE_ALGORITHM',
    ),
    'ARGS_DRIFT_HARD': ('mycelium.action_ledger', 'ARGS_DRIFT_HARD'),
    'ARGS_DRIFT_OFF': ('mycelium.action_ledger', 'ARGS_DRIFT_OFF'),
    'ARGS_DRIFT_POLICIES': ('mycelium.action_ledger', 'ARGS_DRIFT_POLICIES'),
    'ARGS_DRIFT_SOFT': ('mycelium.action_ledger', 'ARGS_DRIFT_SOFT'),
    'ActionLedger': ('mycelium.action_ledger', 'ActionLedger'),
    'AdapterConformanceCase': ('mycelium.provider_conformance', 'AdapterConformanceCase'),
    'AdapterVerificationReport': ('mycelium.provider_conformance', 'AdapterVerificationReport'),
    'AtomicAuditReceiptStorage': ('mycelium.audit_receipt', 'AtomicAuditReceiptStorage'),
    'AtomicCompletionStorage': ('mycelium.completion_contract', 'AtomicCompletionStorage'),
    'AtomicLoopGuardStorage': ('mycelium.loop_guard', 'AtomicLoopGuardStorage'),
    'AtomicScopeGuardStorage': ('mycelium.scope_guard', 'AtomicScopeGuardStorage'),
    'AtomicStateBackend': ('mycelium.storage.atomic_state', 'AtomicStateBackend'),
    'AtomicStateContentionError': ('mycelium.storage.atomic_state', 'AtomicStateContentionError'),
    'AtomicStateError': ('mycelium.storage.atomic_state', 'AtomicStateError'),
    'AtomicStateFlushStorage': ('mycelium.state_flush', 'AtomicStateFlushStorage'),
    'AtomicStateRecord': ('mycelium.storage.atomic_state', 'AtomicStateRecord'),
    'AuditReceiptEmitter': ('mycelium.audit_receipt', 'AuditReceiptEmitter'),
    'AuditReceiptError': ('mycelium.audit_receipt', 'AuditReceiptError'),
    'AuditReceiptRecord': ('mycelium.audit_receipt', 'AuditReceiptRecord'),
    'AuthorityExpiredError': ('mycelium.authority_window', 'AuthorityExpiredError'),
    'AuthorityValidation': ('mycelium.authority_window', 'AuthorityValidation'),
    'AuthorityValidationPhase': ('mycelium.authority_window', 'AuthorityValidationPhase'),
    'BoundAuthority': ('mycelium.authority_window', 'BoundAuthority'),
    'BudgetAccountingError': ('mycelium.budget_guard', 'BudgetAccountingError'),
    'BudgetCeilings': ('mycelium.budget_guard', 'BudgetCeilings'),
    'BudgetGuard': ('mycelium.budget_guard', 'BudgetGuard'),
    'BudgetGuardStorage': ('mycelium.budget_guard', 'BudgetGuardStorage'),
    'BudgetRunState': ('mycelium.budget_guard', 'BudgetRunState'),
    'CONFIG_SCHEMA_ID': ('mycelium.config_schema', 'CONFIG_SCHEMA_ID'),
    'CONFIG_VERSION': ('mycelium.config_schema', 'CONFIG_VERSION'),
    'ClusterVerificationResult': ('mycelium.verify', 'ClusterVerificationResult'),
    'CompleteRunResult': ('mycelium.completion_contract', 'CompleteRunResult'),
    'CompletionContract': ('mycelium.completion_contract', 'CompletionContract'),
    'CompletionError': ('mycelium.completion_contract', 'CompletionError'),
    'CompletionMarkError': ('mycelium.completion_contract', 'CompletionMarkError'),
    'CompletionRefusedError': ('mycelium.completion_contract', 'CompletionRefusedError'),
    'CompletionRunState': ('mycelium.completion_contract', 'CompletionRunState'),
    'CompletionStorage': ('mycelium.completion_contract', 'CompletionStorage'),
    'ConfigError': ('mycelium.config', 'ConfigError'),
    'DEFAULT_CONSECUTIVE_SOFT': ('mycelium.loop_guard', 'DEFAULT_CONSECUTIVE_SOFT'),
    'Decision': ('mycelium.decision', 'Decision'),
    'DecisionEngine': ('mycelium.decision', 'DecisionEngine'),
    'DecisionIntent': ('mycelium.decision', 'DecisionIntent'),
    'DecisionPolicyBundle': ('mycelium.decision', 'DecisionPolicyBundle'),
    'DecisionPredicate': ('mycelium.decision', 'DecisionPredicate'),
    'DecisionSnapshot': ('mycelium.decision', 'DecisionSnapshot'),
    'DeploymentAttestation': ('mycelium.verify', 'DeploymentAttestation'),
    'DestructiveGrant': ('mycelium.destructive_confirm', 'DestructiveGrant'),
    'DestructiveGrantError': ('mycelium.destructive_confirm', 'DestructiveGrantError'),
    'DoctorCheck': ('mycelium.doctor', 'DoctorCheck'),
    'DoctorReport': ('mycelium.doctor', 'DoctorReport'),
    'DoctorStatus': ('mycelium.doctor', 'DoctorStatus'),
    'DttrReport': ('mycelium.outcome_emit', 'DttrReport'),
    'EVIDENCE_CONNECTIVITY': ('mycelium.doctor', 'EVIDENCE_CONNECTIVITY'),
    'EVIDENCE_NOT_VERIFIABLE': ('mycelium.doctor', 'EVIDENCE_NOT_VERIFIABLE'),
    'EVIDENCE_OPERATOR': ('mycelium.doctor', 'EVIDENCE_OPERATOR'),
    'EVIDENCE_RUNTIME': ('mycelium.doctor', 'EVIDENCE_RUNTIME'),
    'EVIDENCE_STATIC': ('mycelium.doctor', 'EVIDENCE_STATIC'),
    'EffectState': ('mycelium.transition', 'EffectState'),
    'EntityGuardError': ('mycelium.entity_guard', 'EntityGuardError'),
    'FanoutOutcomeStorage': ('mycelium.outcome_export', 'FanoutOutcomeStorage'),
    'FileAtomicStateBackend': ('mycelium.storage.atomic_state', 'FileAtomicStateBackend'),
    'FileAuditReceiptStorage': ('mycelium.audit_receipt', 'FileAuditReceiptStorage'),
    'FileBudgetGuardStorage': ('mycelium.budget_guard', 'FileBudgetGuardStorage'),
    'FileCompletionStorage': ('mycelium.completion_contract', 'FileCompletionStorage'),
    'FileLedgerStorage': ('mycelium.action_ledger', 'FileLedgerStorage'),
    'FileLoopGuardStorage': ('mycelium.loop_guard', 'FileLoopGuardStorage'),
    'FileOutcomeStorage': ('mycelium.outcome_emit', 'FileOutcomeStorage'),
    'FileScopeGuardStorage': ('mycelium.scope_guard', 'FileScopeGuardStorage'),
    'FileStateFlushStorage': ('mycelium.state_flush', 'FileStateFlushStorage'),
    'GmailConformanceFixture': ('mycelium.providers', 'GmailConformanceFixture'),
    'GmailReconciler': ('mycelium.providers', 'GmailReconciler'),
    'HandoffLink': ('mycelium.transition', 'HandoffLink'),
    'HistoryGuard': ('mycelium.history_guard', 'HistoryGuard'),
    'HistoryTruncatedError': ('mycelium.history_guard', 'HistoryTruncatedError'),
    'InMemoryAtomicStateBackend': ('mycelium.storage.atomic_state', 'InMemoryAtomicStateBackend'),
    'InMemoryAuditReceiptStorage': ('mycelium.audit_receipt', 'InMemoryAuditReceiptStorage'),
    'InMemoryBudgetGuardStorage': ('mycelium.budget_guard', 'InMemoryBudgetGuardStorage'),
    'InMemoryCompletionStorage': ('mycelium.completion_contract', 'InMemoryCompletionStorage'),
    'InMemoryLedgerStorage': ('mycelium.action_ledger', 'InMemoryLedgerStorage'),
    'InMemoryLoopGuardStorage': ('mycelium.loop_guard', 'InMemoryLoopGuardStorage'),
    'InMemoryOutcomeStorage': ('mycelium.outcome_emit', 'InMemoryOutcomeStorage'),
    'InMemoryScopeGuardStorage': ('mycelium.scope_guard', 'InMemoryScopeGuardStorage'),
    'InMemoryStateFlushStorage': ('mycelium.state_flush', 'InMemoryStateFlushStorage'),
    'IsolationRefused': ('mycelium.verify', 'IsolationRefused'),
    'KIND_LLM': ('mycelium.budget_guard', 'KIND_LLM'),
    'KIND_TOOL': ('mycelium.budget_guard', 'KIND_TOOL'),
    'LeaseValidity': ('mycelium.transition', 'LeaseValidity'),
    'LedgerAlreadyResolvedError': ('mycelium.action_ledger', 'LedgerAlreadyResolvedError'),
    'LedgerEntry': ('mycelium.action_ledger', 'LedgerEntry'),
    'LedgerError': ('mycelium.action_ledger', 'LedgerError'),
    'LedgerHardBlockError': ('mycelium.action_ledger', 'LedgerHardBlockError'),
    'LedgerMigrationError': ('mycelium.ledger_migrations', 'LedgerMigrationError'),
    'LedgerMigrationPlan': ('mycelium.ledger_migrations', 'LedgerMigrationPlan'),
    'LedgerMigrationResult': ('mycelium.ledger_migrations', 'LedgerMigrationResult'),
    'LedgerOutcomeAlreadySetError': ('mycelium.action_ledger', 'LedgerOutcomeAlreadySetError'),
    'LedgerPendingError': ('mycelium.action_ledger', 'LedgerPendingError'),
    'LedgerPollTimeoutError': ('mycelium.action_ledger', 'LedgerPollTimeoutError'),
    'LedgerReleaseRefusedError': ('mycelium.action_ledger', 'LedgerReleaseRefusedError'),
    'LedgerSchemaVersionError': ('mycelium.action_ledger', 'LedgerSchemaVersionError'),
    'LedgerSoftBlockError': ('mycelium.action_ledger', 'LedgerSoftBlockError'),
    'LedgerStorage': ('mycelium.action_ledger', 'LedgerStorage'),
    'LedgerStorageUnavailableError': ('mycelium.action_ledger', 'LedgerStorageUnavailableError'),
    'LedgerWorkerAliveError': ('mycelium.action_ledger', 'LedgerWorkerAliveError'),
    'LlmBudgetAdapter': ('mycelium.budget_llm', 'LlmBudgetAdapter'),
    'LoopGuard': ('mycelium.loop_guard', 'LoopGuard'),
    'LoopGuardStorage': ('mycelium.loop_guard', 'LoopGuardStorage'),
    'LoopRunState': ('mycelium.loop_guard', 'LoopRunState'),
    'MEMORY_STORAGE_POLICIES': ('mycelium.config', 'MEMORY_STORAGE_POLICIES'),
    'MEMORY_STORAGE_POLICY_ERROR': ('mycelium.config', 'MEMORY_STORAGE_POLICY_ERROR'),
    'MEMORY_STORAGE_POLICY_WARN': ('mycelium.config', 'MEMORY_STORAGE_POLICY_WARN'),
    'METRIC_AMBIGUITY_AGE': ('mycelium.outcome_export', 'METRIC_AMBIGUITY_AGE'),
    'METRIC_DECISION_DENIALS': ('mycelium.outcome_export', 'METRIC_DECISION_DENIALS'),
    'METRIC_DEFINITIONS': ('mycelium.outcome_export', 'METRIC_DEFINITIONS'),
    'METRIC_FENCE_REJECTIONS': ('mycelium.outcome_export', 'METRIC_FENCE_REJECTIONS'),
    'METRIC_HARD_BLOCKS': ('mycelium.outcome_export', 'METRIC_HARD_BLOCKS'),
    'METRIC_LEASE_RENEWAL_FAILURES': ('mycelium.outcome_export', 'METRIC_LEASE_RENEWAL_FAILURES'),
    'METRIC_OPERATOR_RELEASES': ('mycelium.outcome_export', 'METRIC_OPERATOR_RELEASES'),
    'METRIC_RECOVERY_TIME': ('mycelium.outcome_export', 'METRIC_RECOVERY_TIME'),
    'MISSING_RUN_ID_POLICIES': ('mycelium.loop_guard', 'MISSING_RUN_ID_POLICIES'),
    'MISSING_RUN_ID_POLICY_ERROR': ('mycelium.loop_guard', 'MISSING_RUN_ID_POLICY_ERROR'),
    'MISSING_RUN_ID_POLICY_WARN': ('mycelium.loop_guard', 'MISSING_RUN_ID_POLICY_WARN'),
    'MISSING_USAGE_POLICIES': ('mycelium.budget_guard', 'MISSING_USAGE_POLICIES'),
    'MISSING_USAGE_POLICY_ERROR': ('mycelium.budget_guard', 'MISSING_USAGE_POLICY_ERROR'),
    'MISSING_USAGE_POLICY_WARN': ('mycelium.budget_guard', 'MISSING_USAGE_POLICY_WARN'),
    'MessageValidationError': ('mycelium.message_validator', 'MessageValidationError'),
    'MessageValidator': ('mycelium.message_validator', 'MessageValidator'),
    'MissingRequestIdentityError': ('mycelium.transition', 'MissingRequestIdentityError'),
    'MissingRunIdentityError': ('mycelium.loop_guard', 'MissingRunIdentityError'),
    'MyceliumConfig': ('mycelium.config', 'MyceliumConfig'),
    'MyceliumConfigModel': ('mycelium.config_schema', 'MyceliumConfigModel'),
    'NamespacedAtomicStorage': ('mycelium.storage.atomic_state', 'NamespacedAtomicStorage'),
    'ON_MISMATCH_HARD': ('mycelium.state_authority', 'ON_MISMATCH_HARD'),
    'ON_MISMATCH_SOFT': ('mycelium.state_authority', 'ON_MISMATCH_SOFT'),
    'ON_MISSING_HARD': ('mycelium.budget_guard', 'ON_MISSING_HARD'),
    'ON_MISSING_METER_MODES': ('mycelium.budget_guard', 'ON_MISSING_METER_MODES'),
    'ON_MISSING_OFF': ('mycelium.budget_guard', 'ON_MISSING_OFF'),
    'ON_MISSING_WARN': ('mycelium.budget_guard', 'ON_MISSING_WARN'),
    'ON_VIOLATION_HARD': ('mycelium.scope_guard', 'ON_VIOLATION_HARD'),
    'ON_VIOLATION_SOFT': ('mycelium.scope_guard', 'ON_VIOLATION_SOFT'),
    'OPERATOR_RESOLUTION_COMPLETED': ('mycelium.action_ledger', 'OPERATOR_RESOLUTION_COMPLETED'),
    'OPERATOR_RESOLUTION_NOT_EXECUTED': (
        'mycelium.action_ledger',
        'OPERATOR_RESOLUTION_NOT_EXECUTED',
    ),
    'OUTCOME_ON_FAILURE_ERROR': ('mycelium.outcome_emit', 'OUTCOME_ON_FAILURE_ERROR'),
    'OUTCOME_ON_FAILURE_POLICIES': ('mycelium.outcome_emit', 'OUTCOME_ON_FAILURE_POLICIES'),
    'OUTCOME_ON_FAILURE_WARN': ('mycelium.outcome_emit', 'OUTCOME_ON_FAILURE_WARN'),
    'OpenTelemetryOutcomeStorage': ('mycelium.outcome_export', 'OpenTelemetryOutcomeStorage'),
    'OperatorAuthorizer': ('mycelium.operator_auth', 'OperatorAuthorizer'),
    'OperatorReleaseRequest': ('mycelium.operator_auth', 'OperatorReleaseRequest'),
    'OutcomeEmitError': ('mycelium.outcome_emit', 'OutcomeEmitError'),
    'OutcomeEmitter': ('mycelium.outcome_emit', 'OutcomeEmitter'),
    'OutcomeMetricPoint': ('mycelium.outcome_export', 'OutcomeMetricPoint'),
    'OutcomeMetricProjector': ('mycelium.outcome_export', 'OutcomeMetricProjector'),
    'OutcomeRow': ('mycelium.outcome_emit', 'OutcomeRow'),
    'OutcomeStorage': ('mycelium.outcome_emit', 'OutcomeStorage'),
    'PAYLOAD_OMITTED': ('mycelium.entity_guard', 'PAYLOAD_OMITTED'),
    'PREDICATE_AUTHORITY': ('mycelium.decision', 'PREDICATE_AUTHORITY'),
    'PREDICATE_DESTINATION_POLICY': ('mycelium.decision', 'PREDICATE_DESTINATION_POLICY'),
    'PREDICATE_DESTRUCTIVE_CONFIRM': ('mycelium.decision', 'PREDICATE_DESTRUCTIVE_CONFIRM'),
    'PREDICATE_SECRET_PROTECTION': ('mycelium.decision', 'PREDICATE_SECRET_PROTECTION'),
    'PREDICATE_USE_TIME_CURRENCY': ('mycelium.decision', 'PREDICATE_USE_TIME_CURRENCY'),
    'PROFILES': ('mycelium.config', 'PROFILES'),
    'PROFILE_DEVELOPMENT': ('mycelium.config', 'PROFILE_DEVELOPMENT'),
    'PROFILE_PRODUCTION': ('mycelium.config', 'PROFILE_PRODUCTION'),
    'PROVIDER_CONFORMANCE_SUITE_VERSION': (
        'mycelium.provider_conformance',
        'PROVIDER_CONFORMANCE_SUITE_VERSION',
    ),
    'PolicyFact': ('mycelium.decision', 'PolicyFact'),
    'PostgresAtomicStateBackend': ('mycelium.storage.atomic_state', 'PostgresAtomicStateBackend'),
    'PostgresBudgetGuardStorage': ('mycelium.budget_guard', 'PostgresBudgetGuardStorage'),
    'PostgresLedgerStorage': ('mycelium.storage.postgres_ledger', 'PostgresLedgerStorage'),
    'PostgresOutcomeStorage': ('mycelium.storage.postgres_outcome', 'PostgresOutcomeStorage'),
    'PostgresTaskLedgerStorage': ('mycelium.storage.postgres_ledger', 'PostgresTaskLedgerStorage'),
    'PredicateVerdict': ('mycelium.decision', 'PredicateVerdict'),
    'PrometheusOutcomeStorage': ('mycelium.outcome_export', 'PrometheusOutcomeStorage'),
    'ProviderCallAudit': ('mycelium.provider_conformance', 'ProviderCallAudit'),
    'ProviderConformanceFixture': ('mycelium.provider_conformance', 'ProviderConformanceFixture'),
    'ProviderKeyValidity': ('mycelium.transition', 'ProviderKeyValidity'),
    'ProviderObservation': ('mycelium.provider_conformance', 'ProviderObservation'),
    'REDACTED_MARKER': ('mycelium.secret_protection', 'REDACTED_MARKER'),
    'REQUEST_IDENTITY_POLICIES': ('mycelium.action_ledger', 'REQUEST_IDENTITY_POLICIES'),
    'REQUEST_IDENTITY_POLICY_DERIVED': (
        'mycelium.action_ledger',
        'REQUEST_IDENTITY_POLICY_DERIVED',
    ),
    'REQUEST_IDENTITY_POLICY_REQUIRE_EXPLICIT': (
        'mycelium.action_ledger',
        'REQUEST_IDENTITY_POLICY_REQUIRE_EXPLICIT',
    ),
    'REQUIRED_PROVIDER_CONFORMANCE_CASES': (
        'mycelium.provider_conformance',
        'REQUIRED_PROVIDER_CONFORMANCE_CASES',
    ),
    'ReconcileResult': ('mycelium.reconcile', 'ReconcileResult'),
    'ReconcileStatus': ('mycelium.reconcile', 'ReconcileStatus'),
    'Reconciler': ('mycelium.reconcile', 'Reconciler'),
    'RedisAtomicStateBackend': ('mycelium.storage.atomic_state', 'RedisAtomicStateBackend'),
    'RedisBudgetGuardStorage': ('mycelium.budget_guard', 'RedisBudgetGuardStorage'),
    'RedisLedgerStorage': ('mycelium.storage.redis_ledger', 'RedisLedgerStorage'),
    'RedisOutcomeStorage': ('mycelium.storage.redis_outcome', 'RedisOutcomeStorage'),
    'RedisTaskLedgerStorage': ('mycelium.storage.redis_ledger', 'RedisTaskLedgerStorage'),
    'RemainingBudget': ('mycelium.budget_guard', 'RemainingBudget'),
    'RetryPermission': ('mycelium.transition', 'RetryPermission'),
    'STATUS_ABANDONED': ('mycelium.completion_contract', 'STATUS_ABANDONED'),
    'STATUS_FAILED': ('mycelium.completion_contract', 'STATUS_FAILED'),
    'STATUS_PENDING': ('mycelium.completion_contract', 'STATUS_PENDING'),
    'STATUS_SUCCESS': ('mycelium.completion_contract', 'STATUS_SUCCESS'),
    'SchemaBuildError': ('mycelium.schema', 'SchemaBuildError'),
    'ScopeGrant': ('mycelium.scope_guard', 'ScopeGrant'),
    'ScopeGuard': ('mycelium.scope_guard', 'ScopeGuard'),
    'ScopeGuardStorage': ('mycelium.scope_guard', 'ScopeGuardStorage'),
    'ScopeRunState': ('mycelium.scope_guard', 'ScopeRunState'),
    'ScopeWidenRefusedError': ('mycelium.scope_guard', 'ScopeWidenRefusedError'),
    'SecretInArgsError': ('mycelium.secret_protection', 'SecretInArgsError'),
    'Session': ('mycelium.session', 'Session'),
    'SideEffectBoundary': ('mycelium.transition', 'SideEffectBoundary'),
    'SideEffectClass': ('mycelium.transition', 'SideEffectClass'),
    'Spendability': ('mycelium.transition', 'Spendability'),
    'SqliteBudgetGuardStorage': ('mycelium.budget_guard', 'SqliteBudgetGuardStorage'),
    'SqliteLedgerStorage': ('mycelium.storage.sqlite_ledger', 'SqliteLedgerStorage'),
    'SqliteTaskLedgerStorage': ('mycelium.storage.sqlite_ledger', 'SqliteTaskLedgerStorage'),
    'StateAuthority': ('mycelium.state_authority', 'StateAuthority'),
    'StateFlush': ('mycelium.state_flush', 'StateFlush'),
    'StateFlushError': ('mycelium.state_flush', 'StateFlushError'),
    'StateMigrationError': ('mycelium.state_migrations', 'StateMigrationError'),
    'StateMigrationPlan': ('mycelium.state_migrations', 'StateMigrationPlan'),
    'StateMigrationResult': ('mycelium.state_migrations', 'StateMigrationResult'),
    'StateSnapshot': ('mycelium.state_flush', 'StateSnapshot'),
    'StaticTokenOperatorAuthorizer': ('mycelium.operator_auth', 'StaticTokenOperatorAuthorizer'),
    'SubtaskMark': ('mycelium.completion_contract', 'SubtaskMark'),
    'TaskFileLedgerStorage': ('mycelium.task_ledger', 'TaskFileLedgerStorage'),
    'TaskInMemoryLedgerStorage': ('mycelium.task_ledger', 'TaskInMemoryLedgerStorage'),
    'TaskLedger': ('mycelium.task_ledger', 'TaskLedger'),
    'TaskLedgerEntry': ('mycelium.task_ledger', 'TaskLedgerEntry'),
    'TaskLedgerError': ('mycelium.task_ledger', 'TaskLedgerError'),
    'TaskLedgerPendingError': ('mycelium.task_ledger', 'TaskLedgerPendingError'),
    'TaskLedgerStorage': ('mycelium.task_ledger', 'TaskLedgerStorage'),
    'TerminalOutcome': ('mycelium.transition', 'TerminalOutcome'),
    'ToolBoundaryError': ('mycelium.tool_boundary', 'ToolBoundaryError'),
    'ToolBoundaryExhaustedError': ('mycelium.tool_boundary', 'ToolBoundaryExhaustedError'),
    'ToolCapability': ('mycelium.transition', 'ToolCapability'),
    'ToolCapabilityDeclarationError': ('mycelium.transition', 'ToolCapabilityDeclarationError'),
    'ToolContract': ('mycelium.contracts', 'ToolContract'),
    'ToolContractModel': ('mycelium.config_schema', 'ToolContractModel'),
    'ToolRegistry': ('mycelium.tool_registry', 'ToolRegistry'),
    'ToolRunner': ('mycelium.tool_runner', 'ToolRunner'),
    'ToolTransitionBinding': ('mycelium.transition', 'ToolTransitionBinding'),
    'TransitionConfig': ('mycelium.config', 'TransitionConfig'),
    'TransitionDttr': ('mycelium.outcome_emit', 'TransitionDttr'),
    'TransitionGate': ('mycelium.transition_resolution', 'TransitionGate'),
    'TransitionPage': ('mycelium.storage.transition_query', 'TransitionPage'),
    'TransitionScope': ('mycelium.transition', 'TransitionScope'),
    'UNCLASSIFIED_POLICY_STRICT': ('mycelium.action_ledger', 'UNCLASSIFIED_POLICY_STRICT'),
    'UNCLASSIFIED_POLICY_WARN': ('mycelium.action_ledger', 'UNCLASSIFIED_POLICY_WARN'),
    'UseTimeCurrencyError': ('mycelium.use_time_currency', 'UseTimeCurrencyError'),
    'UseTimeFact': ('mycelium.use_time_currency', 'UseTimeFact'),
    'UseTimeValidation': ('mycelium.use_time_currency', 'UseTimeValidation'),
    'VERIFIED_ABORT_RUN': ('mycelium.loop_guard', 'VERIFIED_ABORT_RUN'),
    'VERIFIED_ALLOW_ONCE': ('mycelium.loop_guard', 'VERIFIED_ALLOW_ONCE'),
    'VERIFIED_CLEAR': ('mycelium.loop_guard', 'VERIFIED_CLEAR'),
    'VERIFIED_RESOLUTIONS': ('mycelium.loop_guard', 'VERIFIED_RESOLUTIONS'),
    'VIOLATION_BUDGET': ('mycelium.budget_guard', 'VIOLATION_BUDGET'),
    'VIOLATION_BUDGET_WARN': ('mycelium.budget_guard', 'VIOLATION_BUDGET_WARN'),
    'VIOLATION_MISSING': ('mycelium.state_authority', 'VIOLATION_MISSING'),
    'VIOLATION_MISSING_METER': ('mycelium.budget_guard', 'VIOLATION_MISSING_METER'),
    'VIOLATION_MISSING_USAGE': ('mycelium.budget_guard', 'VIOLATION_MISSING_USAGE'),
    'VIOLATION_SUPERSEDED': ('mycelium.state_authority', 'VIOLATION_SUPERSEDED'),
    'VIOLATION_TOOL': ('mycelium.scope_guard', 'VIOLATION_TOOL'),
    'VIOLATION_UNRESOLVED': ('mycelium.state_authority', 'VIOLATION_UNRESOLVED'),
    'ValidatorResult': ('mycelium.use_time_currency', 'ValidatorResult'),
    'VerificationEvidence': ('mycelium.verify', 'VerificationEvidence'),
    'VerificationReport': ('mycelium.verify', 'VerificationReport'),
    'VerificationStatus': ('mycelium.verify', 'VerificationStatus'),
    'WebhookOutcomeStorage': ('mycelium.outcome_export', 'WebhookOutcomeStorage'),
    'action_hash': ('mycelium.loop_guard', 'action_hash'),
    'adapter_report_is_verified': ('mycelium.provider_conformance', 'adapter_report_is_verified'),
    'adapter_report_json': ('mycelium.provider_conformance', 'adapter_report_json'),
    'adapter_report_matches_fixture': (
        'mycelium.provider_conformance',
        'adapter_report_matches_fixture',
    ),
    'apply_budget_guard': ('mycelium.budget_guard', 'apply_budget_guard'),
    'apply_decision_policy': ('mycelium.decision', 'apply_decision_policy'),
    'apply_destructive_confirm': ('mycelium.destructive_confirm', 'apply_destructive_confirm'),
    'apply_entity_guard': ('mycelium.entity_guard', 'apply_entity_guard'),
    'apply_ledger_migration': ('mycelium.ledger_migrations', 'apply_ledger_migration'),
    'apply_loop_guard': ('mycelium.loop_guard', 'apply_loop_guard'),
    'apply_scope_guard': ('mycelium.scope_guard', 'apply_scope_guard'),
    'apply_state_authority': ('mycelium.state_authority', 'apply_state_authority'),
    'apply_state_migration': ('mycelium.state_migrations', 'apply_state_migration'),
    'apply_use_time_currency': ('mycelium.use_time_currency', 'apply_use_time_currency'),
    'bounded': ('mycelium.tool_boundary', 'bounded'),
    'bounded_sync': ('mycelium.tool_boundary', 'bounded_sync'),
    'budget_guard': ('mycelium.budget_guard', 'budget_guard'),
    'budget_guard_sync': ('mycelium.budget_guard', 'budget_guard_sync'),
    'budget_llm': ('mycelium.budget_llm', 'budget_llm'),
    'build_snapshot': ('mycelium.decision', 'build_snapshot'),
    'canonicalize_email': ('mycelium.entity_guard', 'canonicalize_email'),
    'canonicalize_entity_id': ('mycelium.entity_guard', 'canonicalize_entity_id'),
    'canonicalize_host': ('mycelium.entity_guard', 'canonicalize_host'),
    'canonicalize_https_url': ('mycelium.entity_guard', 'canonicalize_https_url'),
    'canonicalize_message_id': ('mycelium.providers', 'canonicalize_message_id'),
    'compute_dttr': ('mycelium.outcome_emit', 'compute_dttr'),
    'compute_dttr_from_storage': ('mycelium.outcome_emit', 'compute_dttr_from_storage'),
    'config_json_schema': ('mycelium.config', 'config_json_schema'),
    'create_adapter_verification_report': (
        'mycelium.provider_conformance',
        'create_adapter_verification_report',
    ),
    'declare_secret_fields': ('mycelium.secret_protection', 'declare_secret_fields'),
    'deployment_attestation_is_verified': ('mycelium.verify', 'deployment_attestation_is_verified'),
    'derive_effect_id': ('mycelium.transition', 'derive_effect_id'),
    'derive_effect_id_for_call': ('mycelium.transition', 'derive_effect_id_for_call'),
    'derive_transition_key': ('mycelium.transition', 'derive_transition_key'),
    'derive_transition_key_for_call': ('mycelium.transition', 'derive_transition_key_for_call'),
    'destructive_grants': ('mycelium.destructive_confirm', 'destructive_grants'),
    'enforce_destructive_confirm': ('mycelium.destructive_confirm', 'enforce_destructive_confirm'),
    'enforce_entity_guard': ('mycelium.entity_guard', 'enforce_entity_guard'),
    'enforce_run_identity': ('mycelium.loop_guard', 'enforce_run_identity'),
    'enforce_use_boundary': ('mycelium.use_time_currency', 'enforce_use_boundary'),
    'execution_scope': ('mycelium.transition', 'execution_scope'),
    'exit_code_for_report': ('mycelium.doctor', 'exit_code_for_report'),
    'export_rows': ('mycelium.outcome_export', 'export_rows'),
    'extract_decision_id': ('mycelium.state_authority', 'extract_decision_id'),
    'extract_model_identity': ('mycelium.budget_llm', 'extract_model_identity'),
    'extract_state_ref': ('mycelium.state_authority', 'extract_state_ref'),
    'extract_token_usage': ('mycelium.budget_llm', 'extract_token_usage'),
    'gate_graph_end': ('mycelium.completion_contract', 'gate_graph_end'),
    'get_active_handoff': ('mycelium.transition', 'get_active_handoff'),
    'get_decision_engine': ('mycelium.decision', 'get_decision_engine'),
    'get_ledger': ('mycelium.action_ledger', 'get_ledger'),
    'get_provider_conformance_fixture': ('mycelium.providers', 'get_provider_conformance_fixture'),
    'get_task_ledger': ('mycelium.task_ledger', 'get_task_ledger'),
    'handoff_scope': ('mycelium.transition', 'handoff_scope'),
    'has_worker_death_evidence': ('mycelium.transition', 'has_worker_death_evidence'),
    'inspect_ledger_schema_versions': (
        'mycelium.ledger_migrations',
        'inspect_ledger_schema_versions',
    ),
    'install_langgraph_llm_budget': ('mycelium.budget_llm', 'install_langgraph_llm_budget'),
    'instrument_crewai_llm': ('mycelium.budget_llm', 'instrument_crewai_llm'),
    'instrument_langgraph_llm': ('mycelium.budget_llm', 'instrument_langgraph_llm'),
    'instrument_llm': ('mycelium.budget_llm', 'instrument_llm'),
    'is_secret_reference': ('mycelium.secret_protection', 'is_secret_reference'),
    'issue_destructive_grant': ('mycelium.destructive_confirm', 'issue_destructive_grant'),
    'ledger': ('mycelium.action_ledger', 'ledger'),
    'ledger_sync': ('mycelium.action_ledger', 'ledger_sync'),
    'load_config': ('mycelium.config', 'load_config'),
    'load_config_from_string': ('mycelium.config', 'load_config_from_string'),
    'loop_guard': ('mycelium.loop_guard', 'loop_guard'),
    'loop_guard_sync': ('mycelium.loop_guard', 'loop_guard_sync'),
    'mark_crossed': ('mycelium.action_ledger', 'mark_crossed'),
    'mark_maybe_crossed': ('mycelium.action_ledger', 'mark_maybe_crossed'),
    'mark_maybe_crossed_async': ('mycelium.action_ledger', 'mark_maybe_crossed_async'),
    'parse_duration_seconds': ('mycelium.budget_guard', 'parse_duration_seconds'),
    'parse_explicit_request_id': ('mycelium.transition', 'parse_explicit_request_id'),
    'parse_run_identity': ('mycelium.loop_guard', 'parse_run_identity'),
    'plan_ledger_migration': ('mycelium.ledger_migrations', 'plan_ledger_migration'),
    'plan_state_migration': ('mycelium.state_migrations', 'plan_state_migration'),
    'protect': ('mycelium.protect', 'protect'),
    'protect_sync': ('mycelium.protect', 'protect_sync'),
    'provider_key_validity': ('mycelium.transition', 'provider_key_validity'),
    'record_external_operation': ('mycelium.action_ledger', 'record_external_operation'),
    'register_decision_predicate': ('mycelium.decision', 'register_decision_predicate'),
    'register_destructive_object_canonicalizer': (
        'mycelium.destructive_confirm',
        'register_destructive_object_canonicalizer',
    ),
    'register_llm_budget_adapter': ('mycelium.budget_llm', 'register_llm_budget_adapter'),
    'register_llm_cost_resolver': ('mycelium.budget_llm', 'register_llm_cost_resolver'),
    'register_secret_hmac_key': ('mycelium.secret_protection', 'register_secret_hmac_key'),
    'register_secret_resolver': ('mycelium.secret_protection', 'register_secret_resolver'),
    'register_terminal_adapter': ('mycelium.completion_contract', 'register_terminal_adapter'),
    'register_use_time_validator': ('mycelium.use_time_currency', 'register_use_time_validator'),
    'registered_llm_budget_adapters': ('mycelium.budget_llm', 'registered_llm_budget_adapters'),
    'registered_terminal_adapters': (
        'mycelium.completion_contract',
        'registered_terminal_adapters',
    ),
    'renew_lease': ('mycelium.action_ledger', 'renew_lease'),
    'repair_transition_fields': ('mycelium.transition_resolution', 'repair_transition_fields'),
    'request_id_from_argument': ('mycelium.transition', 'request_id_from_argument'),
    'reset_completion_terminal_state': (
        'mycelium.completion_contract',
        'reset_completion_terminal_state',
    ),
    'reset_decision_engine': ('mycelium.decision', 'reset_decision_engine'),
    'reset_llm_budget_state': ('mycelium.budget_llm', 'reset_llm_budget_state'),
    'resolve_capability': ('mycelium.transition', 'resolve_capability'),
    'resolve_effect_state': ('mycelium.transition', 'resolve_effect_state'),
    'resolve_lease_validity': ('mycelium.transition', 'resolve_lease_validity'),
    'resolve_loop_scope_key': ('mycelium.loop_guard', 'resolve_loop_scope_key'),
    'resolve_run_id': ('mycelium.loop_guard', 'resolve_run_id'),
    'resolve_secret_reference': ('mycelium.secret_protection', 'resolve_secret_reference'),
    'run_cluster_verify': ('mycelium.verify', 'run_cluster_verify'),
    'run_doctor': ('mycelium.doctor', 'run_doctor'),
    'run_doctor_on_config': ('mycelium.doctor', 'run_doctor_on_config'),
    'run_provider_conformance_cases': (
        'mycelium.provider_conformance',
        'run_provider_conformance_cases',
    ),
    'run_verify': ('mycelium.verify', 'run_verify'),
    'sanitize_secrets': ('mycelium.secret_protection', 'sanitize_secrets'),
    'scan_secrets': ('mycelium.secret_protection', 'scan_secrets'),
    'scope_guard': ('mycelium.scope_guard', 'scope_guard'),
    'scope_guard_sync': ('mycelium.scope_guard', 'scope_guard_sync'),
    'side_effect': ('mycelium.action_ledger', 'side_effect'),
    'side_effect_async': ('mycelium.action_ledger', 'side_effect_async'),
    'state_authority': ('mycelium.state_authority', 'state_authority'),
    'state_authority_sync': ('mycelium.state_authority', 'state_authority_sync'),
    'task_ledger': ('mycelium.task_ledger', 'task_ledger'),
    'task_ledger_sync': ('mycelium.task_ledger', 'task_ledger_sync'),
    'tool_error_message': ('mycelium.tool_boundary', 'tool_error_message'),
    'transition_needs_repair': ('mycelium.transition_resolution', 'transition_needs_repair'),
    'unregister_decision_predicate': ('mycelium.decision', 'unregister_decision_predicate'),
    'upgrade_ledger_entry': ('mycelium.ledger_migrations', 'upgrade_ledger_entry'),
    'use_time_facts': ('mycelium.use_time_currency', 'use_time_facts'),
    'validate_authority_at_use': ('mycelium.authority_window', 'validate_authority_at_use'),
    'validate_contract_call': ('mycelium.contracts', 'validate_contract_call'),
    'verify_adapter_report_signature': (
        'mycelium.provider_conformance',
        'verify_adapter_report_signature',
    ),
    'verify_deployment_attestation_signature': (
        'mycelium.verify',
        'verify_deployment_attestation_signature',
    ),
    'verify_receipt': ('mycelium.audit_receipt', 'verify_receipt'),
    'wrap_final_message': ('mycelium.completion_contract', 'wrap_final_message'),
    'wrap_llm_callable': ('mycelium.budget_llm', 'wrap_llm_callable'),
}

try:
    __version__ = _package_version("mycelium-runtime")
except PackageNotFoundError:  # pragma: no cover - editable/source tree edge
    __version__ = "0.0.0.dev"

__all__ = ['AtomicAuditReceiptStorage',
 'AtomicCompletionStorage',
 'AtomicLoopGuardStorage',
 'AtomicScopeGuardStorage',
 'AtomicStateBackend',
 'AtomicStateContentionError',
 'AtomicStateError',
 'AtomicStateFlushStorage',
 'AtomicStateRecord',
 'FileAtomicStateBackend',
 'InMemoryAtomicStateBackend',
 'NamespacedAtomicStorage',
 'PostgresAtomicStateBackend',
 'RedisAtomicStateBackend',
 'StateMigrationError',
 'StateMigrationPlan',
 'StateMigrationResult',
 'apply_state_migration',
 'plan_state_migration',
 'ActionLedger',
 'LedgerMigrationError',
 'LedgerMigrationPlan',
 'LedgerMigrationResult',
 'LedgerSchemaVersionError',
 'apply_ledger_migration',
 'inspect_ledger_schema_versions',
 'plan_ledger_migration',
 'upgrade_ledger_entry',
 'OperatorAuthorizer',
 'OperatorReleaseRequest',
 'StaticTokenOperatorAuthorizer',
 'FileLedgerStorage',
 'InMemoryLedgerStorage',
 'LedgerAlreadyResolvedError',
 'LedgerEntry',
 'LedgerError',
 'LedgerHardBlockError',
 'LedgerOutcomeAlreadySetError',
 'LedgerWorkerAliveError',
 'LedgerPendingError',
 'LedgerPollTimeoutError',
 'LedgerReleaseRefusedError',
 'LedgerSoftBlockError',
 'LedgerStorage',
 'LedgerStorageUnavailableError',
 'ARGS_DRIFT_OFF',
 'ARGS_DRIFT_SOFT',
 'ARGS_DRIFT_HARD',
 'ARGS_DRIFT_POLICIES',
 'OPERATOR_RESOLUTION_COMPLETED',
 'OPERATOR_RESOLUTION_NOT_EXECUTED',
 'UNCLASSIFIED_POLICY_WARN',
 'UNCLASSIFIED_POLICY_STRICT',
 'REQUEST_IDENTITY_POLICY_DERIVED',
 'REQUEST_IDENTITY_POLICY_REQUIRE_EXPLICIT',
 'REQUEST_IDENTITY_POLICIES',
 'MissingRequestIdentityError',
 'request_id_from_argument',
 'OutcomeEmitError',
 'OUTCOME_ON_FAILURE_WARN',
 'OUTCOME_ON_FAILURE_ERROR',
 'OUTCOME_ON_FAILURE_POLICIES',
 'MEMORY_STORAGE_POLICY_WARN',
 'PROFILE_DEVELOPMENT',
 'PROFILE_PRODUCTION',
 'PROFILES',
 'MEMORY_STORAGE_POLICY_ERROR',
 'MEMORY_STORAGE_POLICIES',
 'Decision',
 'DecisionEngine',
 'DecisionIntent',
 'DecisionPolicyBundle',
 'DecisionPredicate',
 'DecisionSnapshot',
 'PredicateVerdict',
 'PolicyFact',
 'PREDICATE_AUTHORITY',
 'PREDICATE_DESTRUCTIVE_CONFIRM',
 'PREDICATE_DESTINATION_POLICY',
 'PREDICATE_SECRET_PROTECTION',
 'PREDICATE_USE_TIME_CURRENCY',
 'apply_decision_policy',
 'build_snapshot',
 'get_decision_engine',
 'register_decision_predicate',
 'unregister_decision_predicate',
 'reset_decision_engine',
 'GmailReconciler',
 'GmailConformanceFixture',
 'canonicalize_message_id',
 'get_provider_conformance_fixture',
 'ADAPTER_REPORT_SCHEMA_VERSION',
 'ADAPTER_REPORT_SIGNATURE_ALGORITHM',
 'PROVIDER_CONFORMANCE_SUITE_VERSION',
 'REQUIRED_PROVIDER_CONFORMANCE_CASES',
 'AdapterConformanceCase',
 'AdapterVerificationReport',
 'ProviderCallAudit',
 'ProviderConformanceFixture',
 'ProviderObservation',
 'adapter_report_is_verified',
 'adapter_report_json',
 'adapter_report_matches_fixture',
 'create_adapter_verification_report',
 'run_provider_conformance_cases',
 'verify_adapter_report_signature',
 'get_ledger',
 'ledger',
 'ledger_sync',
 'side_effect',
 'side_effect_async',
 'mark_maybe_crossed',
 'mark_maybe_crossed_async',
 'mark_crossed',
 'record_external_operation',
 'renew_lease',
 'Reconciler',
 'ReconcileResult',
 'ReconcileStatus',
 'AuditReceiptEmitter',
 'AuditReceiptError',
 'AuditReceiptRecord',
 'FileAuditReceiptStorage',
 'InMemoryAuditReceiptStorage',
 'verify_receipt',
 'KIND_LLM',
 'MISSING_USAGE_POLICIES',
 'MISSING_USAGE_POLICY_ERROR',
 'MISSING_USAGE_POLICY_WARN',
 'KIND_TOOL',
 'ON_MISSING_HARD',
 'ON_MISSING_METER_MODES',
 'ON_MISSING_OFF',
 'ON_MISSING_WARN',
 'VIOLATION_BUDGET',
 'VIOLATION_BUDGET_WARN',
 'VIOLATION_MISSING_METER',
 'VIOLATION_MISSING_USAGE',
 'BudgetAccountingError',
 'BudgetCeilings',
 'BudgetGuard',
 'BudgetGuardStorage',
 'BudgetRunState',
 'FileBudgetGuardStorage',
 'InMemoryBudgetGuardStorage',
 'PostgresBudgetGuardStorage',
 'RedisBudgetGuardStorage',
 'RemainingBudget',
 'SqliteBudgetGuardStorage',
 'apply_budget_guard',
 'budget_guard',
 'budget_guard_sync',
 'budget_llm',
 'extract_token_usage',
 'LlmBudgetAdapter',
 'extract_model_identity',
 'install_langgraph_llm_budget',
 'instrument_crewai_llm',
 'instrument_langgraph_llm',
 'instrument_llm',
 'register_llm_budget_adapter',
 'register_llm_cost_resolver',
 'registered_llm_budget_adapters',
 'reset_llm_budget_state',
 'wrap_llm_callable',
 'parse_duration_seconds',
 'OutcomeEmitter',
 'OutcomeMetricPoint',
 'OutcomeMetricProjector',
 'OutcomeRow',
 'OutcomeStorage',
 'FanoutOutcomeStorage',
 'FileOutcomeStorage',
 'InMemoryOutcomeStorage',
 'OpenTelemetryOutcomeStorage',
 'PrometheusOutcomeStorage',
 'WebhookOutcomeStorage',
 'METRIC_AMBIGUITY_AGE',
 'METRIC_DECISION_DENIALS',
 'METRIC_DEFINITIONS',
 'METRIC_FENCE_REJECTIONS',
 'METRIC_HARD_BLOCKS',
 'METRIC_LEASE_RENEWAL_FAILURES',
 'METRIC_OPERATOR_RELEASES',
 'METRIC_RECOVERY_TIME',
 'PostgresOutcomeStorage',
 'RedisOutcomeStorage',
 'DttrReport',
 'TransitionDttr',
 'compute_dttr',
 'compute_dttr_from_storage',
 'export_rows',
 'TaskFileLedgerStorage',
 'TaskInMemoryLedgerStorage',
 'TaskLedger',
 'TaskLedgerEntry',
 'TaskLedgerError',
 'TaskLedgerPendingError',
 'TaskLedgerStorage',
 'RedisLedgerStorage',
 'RedisTaskLedgerStorage',
 'PostgresLedgerStorage',
 'PostgresTaskLedgerStorage',
 'SqliteLedgerStorage',
 'SqliteTaskLedgerStorage',
 'TransitionPage',
 'get_task_ledger',
 'task_ledger',
 'task_ledger_sync',
 'ConfigError',
 'CONFIG_SCHEMA_ID',
 'CONFIG_VERSION',
 'MyceliumConfig',
 'MyceliumConfigModel',
 'TransitionConfig',
 'config_json_schema',
 'DoctorCheck',
 'DoctorReport',
 'DoctorStatus',
 'EVIDENCE_CONNECTIVITY',
 'EVIDENCE_NOT_VERIFIABLE',
 'EVIDENCE_OPERATOR',
 'EVIDENCE_RUNTIME',
 'EVIDENCE_STATIC',
 'exit_code_for_report',
 'run_doctor',
 'run_doctor_on_config',
 'ClusterVerificationResult',
 'DeploymentAttestation',
 'IsolationRefused',
 'VerificationEvidence',
 'VerificationReport',
 'VerificationStatus',
 'deployment_attestation_is_verified',
 'run_cluster_verify',
 'run_verify',
 'verify_deployment_attestation_signature',
 'SideEffectClass',
 'SideEffectBoundary',
 'Spendability',
 'ToolCapability',
 'ToolCapabilityDeclarationError',
 'resolve_capability',
 'RetryPermission',
 'TerminalOutcome',
 'EffectState',
 'resolve_effect_state',
 'LeaseValidity',
 'ProviderKeyValidity',
 'TransitionGate',
 'ToolTransitionBinding',
 'HandoffLink',
 'TransitionScope',
 'derive_effect_id',
 'derive_effect_id_for_call',
 'derive_transition_key',
 'derive_transition_key_for_call',
 'parse_explicit_request_id',
 'execution_scope',
 'get_active_handoff',
 'handoff_scope',
 'resolve_lease_validity',
 'provider_key_validity',
 'has_worker_death_evidence',
 'repair_transition_fields',
 'transition_needs_repair',
 'load_config',
 'load_config_from_string',
 'protect',
 'protect_sync',
 'PAYLOAD_OMITTED',
 'AuthorityExpiredError',
 'AuthorityValidation',
 'AuthorityValidationPhase',
 'BoundAuthority',
 'validate_authority_at_use',
 'UseTimeCurrencyError',
 'UseTimeFact',
 'UseTimeValidation',
 'ValidatorResult',
 'apply_use_time_currency',
 'enforce_use_boundary',
 'register_use_time_validator',
 'use_time_facts',
 'DestructiveGrant',
 'DestructiveGrantError',
 'apply_destructive_confirm',
 'destructive_grants',
 'enforce_destructive_confirm',
 'issue_destructive_grant',
 'register_destructive_object_canonicalizer',
 'EntityGuardError',
 'apply_entity_guard',
 'canonicalize_email',
 'canonicalize_entity_id',
 'canonicalize_host',
 'canonicalize_https_url',
 'enforce_entity_guard',
 'REDACTED_MARKER',
 'SecretInArgsError',
 'declare_secret_fields',
 'is_secret_reference',
 'register_secret_hmac_key',
 'register_secret_resolver',
 'resolve_secret_reference',
 'sanitize_secrets',
 'scan_secrets',
 'Session',
 'StateFlush',
 'StateFlushError',
 'StateSnapshot',
 'FileStateFlushStorage',
 'InMemoryStateFlushStorage',
 'MessageValidator',
 'MessageValidationError',
 'HistoryGuard',
 'HistoryTruncatedError',
 'DEFAULT_CONSECUTIVE_SOFT',
 'MISSING_RUN_ID_POLICIES',
 'MISSING_RUN_ID_POLICY_ERROR',
 'MISSING_RUN_ID_POLICY_WARN',
 'VERIFIED_ABORT_RUN',
 'VERIFIED_ALLOW_ONCE',
 'VERIFIED_CLEAR',
 'VERIFIED_RESOLUTIONS',
 'FileLoopGuardStorage',
 'InMemoryLoopGuardStorage',
 'LoopGuard',
 'LoopGuardStorage',
 'LoopRunState',
 'MissingRunIdentityError',
 'action_hash',
 'apply_loop_guard',
 'enforce_run_identity',
 'loop_guard',
 'loop_guard_sync',
 'parse_run_identity',
 'resolve_loop_scope_key',
 'resolve_run_id',
 'ON_VIOLATION_HARD',
 'ON_VIOLATION_SOFT',
 'VIOLATION_TOOL',
 'FileScopeGuardStorage',
 'InMemoryScopeGuardStorage',
 'ScopeGrant',
 'ScopeGuard',
 'ScopeGuardStorage',
 'ScopeRunState',
 'ScopeWidenRefusedError',
 'apply_scope_guard',
 'scope_guard',
 'scope_guard_sync',
 'STATUS_ABANDONED',
 'STATUS_FAILED',
 'STATUS_PENDING',
 'STATUS_SUCCESS',
 'CompleteRunResult',
 'CompletionContract',
 'CompletionError',
 'CompletionMarkError',
 'CompletionRefusedError',
 'CompletionRunState',
 'CompletionStorage',
 'FileCompletionStorage',
 'InMemoryCompletionStorage',
 'SubtaskMark',
 'gate_graph_end',
 'register_terminal_adapter',
 'registered_terminal_adapters',
 'reset_completion_terminal_state',
 'wrap_final_message',
 'ON_MISMATCH_HARD',
 'ON_MISMATCH_SOFT',
 'VIOLATION_MISSING',
 'VIOLATION_SUPERSEDED',
 'VIOLATION_UNRESOLVED',
 'StateAuthority',
 'apply_state_authority',
 'extract_decision_id',
 'extract_state_ref',
 'state_authority',
 'state_authority_sync',
 'bounded',
 'bounded_sync',
 'SchemaBuildError',
 'ToolContract',
 'ToolContractModel',
 'validate_contract_call',
 'ToolBoundaryError',
 'ToolBoundaryExhaustedError',
 'tool_error_message',
 'ToolRegistry',
 'ToolRunner',
 '__version__']


class _LazyModule(_ModuleType):
    def __getattribute__(self, name: str):
        # Importing a submodule automatically places it on the package.  If
        # its basename is also a historical root export (for example
        # ``task_ledger``), resolve the export instead of leaking that module.
        lazy_imports = _ModuleType.__getattribute__(self, "__dict__").get("_LAZY_IMPORTS", {})
        if name in lazy_imports:
            value = _ModuleType.__getattribute__(self, "__dict__").get(name)
            if isinstance(value, _ModuleType) or value is None:
                return self.__getattr__(name)
        return _ModuleType.__getattribute__(self, name)


def __getattr__(name: str):
    """Load a documented root export or historical submodule on demand."""
    if name in _PUBLIC_SUBMODULES:
        value = _import_module(f"{__name__}.{name}")
        globals()[name] = value
        return value
    try:
        module_name, attribute_name = _LAZY_IMPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    value = getattr(_import_module(module_name), attribute_name)
    globals()[name] = value
    return value


_PUBLIC_SUBMODULES = {
    "action_ledger", "audit_receipt", "authority_window", "cache",
    "completion_contract", "config", "config_parser", "config_policies",
    "config_schema", "config_types", "contracts", "decision",
    "destructive_confirm", "doctor", "entity_guard", "history_guard",
    "integrations", "ledger_context", "ledger_execution", "ledger_identity",
    "ledger_migrations", "ledger_model", "ledger_recovery", "ledger_storage",
    "message_validator", "operator_auth", "outcome_emit", "outcome_export",
    "provider_conformance", "providers", "reconcile", "runtime_builder",
    "schema", "secret_protection", "session", "state_authority", "state_flush",
    "state_migrations", "storage", "tool_boundary", "tool_registry", "tool_runner",
    "transition", "transition_resolution", "use_time_currency", "verify",
}


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__) | _PUBLIC_SUBMODULES)

# Keep root export lookup authoritative even when Python attaches a same-named
# submodule to the package during a lazy import.
_sys.modules[__name__].__class__ = _LazyModule
# ``from __future__ import annotations`` exposes its feature marker on some
# supported interpreters; it is implementation detail, not a package export.
globals().pop("annotations", None)
