"""Generated documentation and examples for the versioned config contract."""

from __future__ import annotations

import json
from typing import Any

import yaml

from mycelium.config_schema import CONFIG_VERSION, MyceliumConfigModel, config_json_schema

_BASELINE_EXAMPLE: dict[str, Any] = {
    "config_version": CONFIG_VERSION,
    "profile": "development",
    "transition": {
        "agent_id": "example-agent",
        "policy_version": "1",
        "reclaim_requires_death_signal": True,
    },
    "state_backend": {"storage": "file", "path": "./mycelium-state.json"},
    "action_ledger": {
        "storage": "sqlite",
        "path": "./mycelium-ledger.db",
        "tools": [],
        "unclassified_policy": "strict",
    },
    "tools": {},
}


def config_example_data() -> dict[str, Any]:
    """Return a model-validated, conservative starter configuration."""

    model = MyceliumConfigModel.model_validate(_BASELINE_EXAMPLE)
    return model.model_dump(
        mode="json",
        exclude_none=True,
        exclude_unset=True,
    )


def render_config_example() -> str:
    """Render the current model-validated starter as YAML."""

    body = yaml.safe_dump(config_example_data(), sort_keys=False)
    return (
        "# Generated by: python scripts/generate_config_artifacts.py\n"
        "# IDE schema: mycelium config schema -o mycelium.schema.json\n" + body
    )


def _schema_type(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return str(node["$ref"]).rsplit("/", 1)[-1].removesuffix("ConfigModel")
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return " | ".join(json.dumps(item) for item in node["enum"])
    if "anyOf" in node:
        return " | ".join(_schema_type(item) for item in node["anyOf"])
    node_type = node.get("type", "any")
    if node_type == "array":
        return f"array[{_schema_type(node.get('items', {}))}]"
    if node_type == "object" and isinstance(node.get("additionalProperties"), dict):
        return f"object[string, {_schema_type(node['additionalProperties'])}]"
    return str(node_type)


def _default_text(node: dict[str, Any], *, required: bool) -> str:
    if "default" in node:
        return f"`{json.dumps(node['default'])}`"
    return "required" if required else "—"


def _section_table(title: str, node: dict[str, Any]) -> list[str]:
    properties = node.get("properties", {})
    required = set(node.get("required", []))
    lines = [f"## {title}", ""]
    description = node.get("description")
    if description:
        lines.extend([str(description), ""])
    lines.extend(
        [
            "| Field | Type | Default | Description |",
            "| --- | --- | --- | --- |",
        ]
    )
    for name, field in properties.items():
        field_description = str(field.get("description", "")).replace("|", "\\|") or "—"
        field_type = _schema_type(field).replace("|", "\\|")
        lines.append(
            f"| `{name}` | `{field_type}` | "
            f"{_default_text(field, required=name in required)} | {field_description} |"
        )
    lines.append("")
    return lines


def render_config_reference() -> str:
    """Render deterministic Markdown directly from the current JSON Schema."""

    schema = config_json_schema()
    lines = [
        "<!-- Generated by scripts/generate_config_artifacts.py; do not edit by hand. -->",
        "# Mycelium configuration reference",
        "",
        f"Configuration format version: `{CONFIG_VERSION}`.",
        "",
        "Generate the machine-readable schema with `mycelium config schema`.",
        "Generate a validated starter with `mycelium config example`.",
        "",
        "## Control index",
        "",
        "The tables below use schema model names; the corresponding YAML keys are:",
        "",
        "| YAML section | Field reference |",
        "| --- | --- |",
        "| `budget` | [Budget](#budget) |",
        "| `completion` | [Completion](#completion) |",
        "| `loop_guard` | [LoopGuard](#loopguard) |",
        "| `scope_guard` | [ScopeGuard](#scopeguard) |",
        "| `state_authority` | [StateAuthority](#stateauthority) |",
        "| `secret_args` | [SecretArgs](#secretargs) |",
        "| `entity_guard` | [EntityGuard](#entityguard), "
        "[destinations](#entitydestination), [allowlists](#entityallow) |",
        "| `destructive_confirm` | [DestructiveConfirm](#destructiveconfirm), "
        "[tools](#destructivetool), [objects](#destructiveobject), "
        "[grants](#destructivegrant) |",
        "| `authority_window` | [AuthorityWindow](#authoritywindow) |",
        "| `use_time_currency` | [UseTimeCurrency](#usetimecurrency), "
        "[tools](#usetimetool), [facts](#usetimefact), [subjects](#factsubject) |",
        "| `history_guard` | [HistoryGuard](#historyguard) |",
        "| `message_validator` | [MessageValidator](#messagevalidator) |",
        "",
        "Defaults in the tables describe the structural schema. A `null` or omitted",
        "value can select a runtime default or inherit a backend; section descriptions",
        "explain those choices. Storage support varies by control, so use its own",
        "`storage` row rather than the common Storage table to choose a backend.",
        "",
    ]
    lines.extend(_section_table("Top-level fields", schema))
    for name, definition in schema.get("$defs", {}).items():
        title = str(definition.get("title", name)).removesuffix("ConfigModel")
        lines.extend(_section_table(title, definition))
    lines.extend(
        [
            "## Activation and recovery boundaries",
            "",
            "Omit `budget`, `completion`, `loop_guard`, `scope_guard`, or `history_guard`",
            "to disable that control. These sections reject `enabled` and unknown keys.",
            "Existing per-tool boolean overrides remain supported where documented.",
            "",
            "For configured state authority, Doctor resolves and inspects the synchronous",
            "host callable without invoking it. The host must supply current canonical state",
            "and use the wrapper. Set `require_state_ref: true` when missing or unresolved",
            "state must block an action; the default permits calls without state references.",
            "",
            "Composite recovery is a Python API, not a top-level YAML section. See",
            "[durable composite recovery](COMPOSITE_RECOVERY.md) for `@composite`,",
            "`composite_choice()`, `composite_items()`, definition pinning, and bounded syntax.",
            "The experimental sidecar uses explicit manifests; see",
            "[sidecar self-hosting](SELF_HOSTING.md) for supported deployment profiles.",
            "",
            "For wiring and limitations of the opt-in action controls, see the",
            "[SDK reference](../README.md). URL allowlists do not enforce process-wide egress.",
            "Redis persistence is operator-asserted; Doctor reports an advisory warning",
            "and does not inspect AOF/RDB or the server's data-loss policy.",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


__all__ = [
    "config_example_data",
    "render_config_example",
    "render_config_reference",
]
